insert into MEMBER (email, nickname, pwd, name, ph, age) values ('bhs123@bhs.com', 'admin', '1234', '관리자', '01000000000', 30);
insert into MEMBER (email, nickname, pwd, name, ph, age) values ('sol@bhs.com', 'sol', '1234', '배솔반', '01012341234', 28);
insert into MEMBER (email, nickname, pwd, name, ph, age) values ('hsk@bhs.com', 'hsk', '1234', '홍수경', '01003568900', 20);
insert into MEMBER (email, nickname, pwd, name, ph, age) values ('sang@bhs.com', 'sang', '1234', '서상록', '01014702580', 25);
commit;

Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카레','서울 성북구 성북로 62-1','아시아',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('야상해','서울 용산구 이태원로23길 6','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('문치비','제주 서귀포시 신서로32번길 14','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('가산통통생고기','서울 금천구 가산디지털1로 151','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('로','서울 금천구 디지털로9길 47 ','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오늘돈카츠','서울 금천구 가산디지털1로 171','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('일월카츠','서울 종로구 계동길 17','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('어리틀케틀','서울 종로구 필운대로 48','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('애즈라이크','서울 종로구 효자로7길 23','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('화목순대국','서울 영등포구 여의대방로 383','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('과자방','서울 마포구 큰우물로 16','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('폴베리','서울 마포구 포은로 40','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('고도','서울 마포구 월드컵북로 121-8','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('올레무스','서울 서대문구 연희로5길 58','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('삼공','서울 마포구 망원로1길 12','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('샐러마리','서울 마포구 망원로 55-3','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('밀토니아','서울 마포구 월드컵로7길 73','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('모센즈스위트','서울 마포구 어울마당로 51-1','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('해남순대국','서울 중구 다산로8길 8','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('Better than alcohol','서울 마포구 희우정로16길 50','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('라바즈','서울 마포구 월드컵로13길 19-23','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('옥동식','서울 마포구 양화로7길 44-10','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('브뤼서리 서교','서울 마포구 월드컵로12길 10','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('츄이구이브레드','서울 마포구 토정로3안길 18','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('미스타교자','서울 마포구 동교로 106','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('미필담','서울 마포구 성지3길 22','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('교다이야','서울 마포구 성지길 39','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('난','서울 마포구 토정로3길 22','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('395빵집','서울 마포구 양화로8길 25-3','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('Mon Cafe Gregory','서울 마포구 양화로6길 84','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('씨네마포','서울 마포구 독막로9길 3-3','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('umoae','서울 마포구 양화로6길 99-5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('파이피플','서울 마포구 독막로7길 45','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('버터밀크','서울 마포구 와우산로 130','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('릴리우드','서울 마포구 서강로11길 18','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('모뎐','서울 마포구 동교로19길 52-7','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('스트로베리32','서울 마포구 연남로5길 8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('조앤도슨','서울 마포구 동교로41길 31','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('제스티살룬','서울 마포구 연희로 31','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('도부','서울 마포구 동교로51길 77-11 ','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('하이파이','서울 서대문구 연희로11가길 39','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('보연희','서울 서대문구 연희맛로 17-63','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('콜드레시피','서울 서대문구 연희로11라길 2','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('Jason95','서울 서대문구 연희로11길 57','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('폴앤폴리나','서울 서대문구 연희로11길 56','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('애니브','서울 서대문구 연희로11가길 8-8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('온고','서울 서대문구 연희로11길 71','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('티그레 서울','서울 은평구 연서로29길 34','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('03 인앤아웃','서울 서대문구 연희로11길 57','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('lodge190','서울 서대문구 홍제천로 190','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('YM COFFEE HOUSE','서울 은평구 연서로29길 21-8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('크림 레스토랑 앤 디저트바','경기 고양시 덕양구 동송로 70','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('케익크','경기 고양시 일산동구 일산로358번길 20','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('일오삼간장게장','인천 강화군 양도면 중앙로1052번길 16','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('벨팡','인천 강화군 길상면 온수길 32','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('정정','서울 마포구 백범로24길 27','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('프릳츠 도화점','서울 마포구 새창로2길 17','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('정대포','서울 마포구 도화길 52 ','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('타쿠미야','서울 마포구 백범로 152 102동','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('비파티세리 공덕점','서울 마포구 마포대로14길 4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('락희','서울 용산구 효창원로15길 26-4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('킵햅','서울 용산구 원효로97길 37','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('말라카이트','서울 용산구 원효로97길 13','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('식캣사인','서울 용산구 원효로83길 7-2','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('유용욱바베큐연구소','서울 용산구 한강대로84길 5-7','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('남영돈','서울 용산구 한강대로80길 17','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('끌레망꾸꾸','서울 용산구 소월로2길 27','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('TAFFIN','서울 용산구 후암로 20','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('진1926','서울 용산구 한강대로 366','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오제제','서울 중구 세종대로 136','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('고려삼계탕','서울 중구 서소문로11길 1','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('힐사이드테이블','서울 종로구 경희궁2길 7','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('고트델리 서촌','서울 종로구 필운대로5가길 13','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('고트델리 문래 ','서울 영등포구 도림로139길 14','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('풍류관','서울 종로구 필운대로5나길 20-12 ','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('레종데트르','서울 종로구 자하문로7길 67-2','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('에디션덴마크 서촌','서울 종로구 자하문로9길 24','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('더마틴','서울 종로구 자하문로 54-1','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('동감','서울 종로구 자하문로28길 5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('큔','서울 종로구 자하문로26길 17-2','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('안암','서울 종로구 북촌로5길 10','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('소금집델리 안국','서울 종로구 북촌로4길 19','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('소금집델리 망원','서울 마포구 월드컵로19길 14','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('맷차','서울 중구 명동9길 17','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('노우즈안국','서울 종로구 계동길 17','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('깡통만두','서울 종로구 북촌로2길 5-6','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('코인','서울 중구 명동6길 10','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('가무','서울 중구 명동4길 16','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카페타자기','서울 용산구 신흥로 97-5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('토스티데이즈','서울 용산구 신흥로 97-6','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('잎차','서울 용산구 신흥로 95-21','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('르몽블랑','서울 용산구 신흥로 99-4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('노스트레스버거','서울 용산구 신흥로 62','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('르페셰미뇽','서울 용산구 녹사평대로40가길 3-3','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('라이너스바베큐','서울 용산구 이태원로 136-13','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('심야식당','서울 마포구 독막로9길 43','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('알페도','서울 용산구 이태원로 174','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('끌라시끄','서울 용산구 우사단로4길 28','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('뽀르누서울','서울 용산구 서빙고로91나길 46','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오아시스 한남','서울 용산구 이태원로45길 30','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('제이엘 디저트바','서울 용산구 이태원로55가길 38','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('치즈플로','서울 용산구 이태원로49길 19','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('Summer Lane','서울 용산구 이태원로55가길 49','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('수르기','서울 용산구 이태원로42길 32','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('샐러드셀러','서울 용산구 대사관로5길 28','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('월간식당','서울 용산구 이태원로54길 58-12','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('재인','서울 용산구 이태원로54길 48','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('소프트팬트리','서울 용산구 한남대로27길 33','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('레종데트르 한남','서울 용산구 이태원로42길 62','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('패션5','서울 용산구 이태원로 272','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('올드페리도넛','서울 용산구 한남대로27길 66','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('디핀옥수','서울 성동구 독서당로 194','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('해남순대국','서울 중구 다산로8길 8','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('퀸즈베리도넛하우스','서울 중구 다산로19길 29','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('드엠','서울 종로구 동순라길 126-3 ','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('아베베 베이커리 서울','서울 종로구 청계천로 201','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('우래옥','서울 중구 창경궁로 62-29','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('키이로','서울 종로구 창경궁로26길 41-3','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('겨울과봄사이','서울 성북구 성북로8길 12-6','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('하단','서울 성북구 성북로6길 14','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('유목커피바','서울 성북구 동소문로24길 47','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('기쁜소식','서울 성북구 종암로10길 26','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('드소영','서울 성동구 고산자로6길 24','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('신가네 칼국수','서울 노원구 공릉로59나길 78-14','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('모츠커피','서울 광진구 군자로3길 14','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('프롤라','서울 성동구 연무장17길 5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('성수동 대림창고 갤러리','서울 성동구 성수이로 78','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('세스크멘슬','서울 성동구 성수이로14길 7','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('FINZ','서울 성동구 성수일로3길 4-13','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('에디션덴마크 성수','서울 성동구 성수일로 1','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('유어네이키드치즈','서울 성동구 왕십리로10길 6','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('치즈포레스트','서울 성동구 뚝섬로3길 9','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('감도','서울 성동구 왕십리로 83-21','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('앤드밀 성수','서울 성동구 연무장3길 5-1','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('범가','서울 광진구 광장로 58-1','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('얌얌카츠','서울 강동구 천호옛14길 22','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카쿠','서울 강동구 성안로 45','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('디저티스트','서울 송파구 송파대로48길 37','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('큐뮬러스','서울 서초구 강남대로 299','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('진저베어','서울 송파구 백제고분로41길 43-7','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('빌즈','서울 송파구 올림픽로 300 롯데월드몰','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('파브리케','서울 송파구 법원로11길 25','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('껠끄쇼즈','서울 강남구 도곡로70길 5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('시트롱','서울 강남구 논현로26길 56 ','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('앨리스 프로젝트','서울 서초구 양재천로 107-4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('문화시민 서울','서울 강남구 강남대로62길 35','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('% ARABICA','서울 강남구 영동대로 513','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('로흐','서울 강남구 테헤란로13길 17 ','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('꼼다비뛰드','서울 강남구 강남대로110길 62','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('덕자네 방앗간','서울 서초구 서초대로77길 62','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('레자미오네뜨','서울 강남구 학동로5길 5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('당옥','서울 강남구 강남대로162길 22','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('쇼토','서울 강남구 압구정로18길 14-6','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('현우동','서울 강남구 논현로149길 53','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('로바타탄요','서울 강남구 압구정로28길 49 ','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('램브라튼','서울 강남구 압구정로10길 30-10','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('소울브레드','서울 서초구 바우뫼로7길 27','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('노스티모','서울 서초구 서초대로 125','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카페 아뜰리에','서울 서초구 방배천로4길 48','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('주','서울 서초구 동광로19길 16','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('묘오또','서울 서초구 방배로28길 16','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('태양커피','서울 서초구 서초대로25길 55','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오리에','서울 서초구 서초대로27길 21','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('바타드브레드','서울 서초구 방배로20길 33','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('브루클린 더 버거조인트','서울 서초구 서래로2길 27','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('곳간집','서울 관악구 인헌3나길 26','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('뉴욕택시디저트','서울 관악구 남부순환로 1870','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('앙뿌','서울 관악구 관악로14가길 6','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('THE한강','서울 동작구 노량진로32길 29-6','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('보배반점','서울 금천구 가산디지털2로 108 111호','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오한수우육면가 한라원앤원타워점','서울 금천구 가산디지털2로 101','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('가산물갈비&백년불고기','서울 금천구 가산디지털1로 128','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('박가라멘','서울 금천구 디지털로 121','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('고칸','서울 금천구 가산디지털2로 101 204호','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('꿈떡꿈떡 한라원앤원타워점','서울 금천구 가산디지털2로 101 107호','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('본래순대 한라원앤원타워점','서울 금천구 가산디지털2로 101 201호','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('마라강호 한라원앤원타워점','서울 금천구 가산디지털2로 101 115호','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('디저트39 가산한라원앤원점','서울 금천구 가산디지털2로 101 117호','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('파란만잔 가산한라원앤원점','서울 금천구 가산디지털2로 101 104호','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('메가MGC커피 가산한라원앤원점','서울 금천구 가산디지털2로 101 111호','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('동남집','서울 금천구 가산디지털1로 149','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오키소바','서울 금천구 가산디지털1로 128','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('망향비빔국수 가산디지털단지점','서울 금천구 가산디지털1로 186','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('얌샘김밥 가산한라원앤원점','서울 금천구 가산디지털2로 101 121호','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('곰이네 고래빵','경기 안양시 동안구 동편로49번길 19','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('미니아양꼬치&마라탕','경기 안양시 동안구 평촌대로 120','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('잇다제과','경기 남양주시 진접읍 광릉수목원로 179-18','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('성심당 본점','대전 중구 대종로480번길 15','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('성심당 케익부띠끄','대전 중구 대종로 480','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('로니로티','서울 노원구 상계로 63-7','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('파셀','대전 유성구 죽동로298번길 31','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오쓰세이로무시','서울 영등포구 국제금융로2길 36','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('정동문화사','대전 동구 태전로 22','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('100sheets','대전 중구 대흥로121번길 36','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('진로집','대전 중구 중교로 45-5','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('까멜리아 고창','전북 고창군 고창읍 고인돌대로 1897-11','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('태평소국밥','대전 유성구 온천동로65번길 50','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('그린베이커리','대전 유성구 테크노4로 98-8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('신덕식당','전북 고창군 아산면 선운사로 8','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('만석닭강정','강원 속초시 청초호반로 72','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('타이드','부산 해운대구 달맞이길62번길 53','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('호랑이젤라떡','부산 해운대구 달맞이길62번길 38','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('뮬리노 에스프레소바 한남','서울 용산구 이태원로54길 68-5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('은쏨','부산 해운대구 우동1로85번길 8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('나가하마만게츠','부산 해운대구 우동1로 57','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('빨간떡볶이','부산 해운대구 우동1로20번가길 4','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('리틀오스','부산 수영구 수영로510번길 42','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('서희와제과','부산 수영구 광남로 89','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('바닷마을과자점','부산 수영구 광남로48번길 43','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('고옥','부산 수영구 광남로 6 남천동 12-8번지','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('인크커피','서울 금천구 가산디지털2로 127-20','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('라라관 건대입구점','서울 광진구 동일로18길 10','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('뚤리','서울 서대문구 홍제천로 198','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('당도','서울 마포구 포은로 106','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카페톤','서울 마포구 성미산로1길 26','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('하이놀리','서울 마포구 망원로1길 12','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('젠제로','서울 강남구 선릉로126길 14','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('녹기전에','서울 마포구 백범로 127-24','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('담택','서울 마포구 월드컵로8길 34','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('뉴러우멘관즈','부산 수영구 수영로388번길 25-4','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오복식당','전북 고창군 성내면 근촌로 3','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('봉밀가','서울 강남구 선릉로 664','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('신발원','부산 동구 대영로243번길 62','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('초량온당','부산 동구 초량중로 135','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('이재모피자','부산 중구 광복중앙로 31','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('희와제과','부산 부산진구 전포대로246번길 6','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('구프','부산 부산진구 동성로 25','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('퍼프베이커리','부산 부산진구 동천로 56 1층','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('쿠루미과자점','부산 동래구 온천천로 71-1','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('수완초밥','광주 광산구 임방울대로 347','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('바오하우스','부산 부산진구 서전로38번길 62-9','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('크리미','부산 부산진구 서전로38번길 43-13','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('듀랩','부산 부산진구 서전로46번길 10-7','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('브리앙 ','부산 동래구 온천장로119번길 26','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('가마솥족발','경북 경주시 봉황로 39-1','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('엘로우','경북 경주시 경감로 375-16','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('윈드윈','대구 중구 달구벌대로405길 42','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('수수케키','대구 중구 명륜로23길 46','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오브너','대구 중구 봉산문화1길 13','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카페 앙코르','대구 중구 동덕로30길 104-4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('샬로우커피','대구 중구 국채보상로150길 31','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오이','대구 중구 달구벌대로445길 26-18','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오가닉모가','대구 중구 동덕로 48-5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('루시드','대구 중구 동성로4길 94','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('동아식당','대구 중구 국채보상로125길 14','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('태산만두','대구 중구 달구벌대로 2109-32','분식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('두아몽떼','대구 중구 약령길 20','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('이천우화','대구 남구 이천로 137','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('잔물결','제주 제주시 한림읍 금능길 58-1','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('그시절그짬뽕','제주 제주시 한림읍 한림북동길 7 ','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('시골길','제주 제주시 연동13길 9','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('흑돈가','제주 제주시 한라대학로 11','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('선하다선','제주 제주시 조천읍 북선로 322-15','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('선흘방주할머니식당','제주 제주시 조천읍 선교로 212','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('요요무문','제주 제주시 구좌읍 해맞이해안로 1102','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('명진전복','제주 제주시 구좌읍 해맞이해안로 1282','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('친봉산장','제주 서귀포시 하신상로 417','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('제주순메밀막국수','제주 서귀포시 안덕면 녹차분재로 60','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('가타쯔무리','서울 서대문구 명지대길 72','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('연의양과','부산 부산진구 서전로37번길 20','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('맥도날드 가산비즈니스센터점','서울 금천구 가산디지털1로 165 ','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('신수로','서울 마포구 토정로 221','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('버터밀크','서울 마포구 와우산로 130','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('코운코운','서울 마포구 와우산로3길 16','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('세상끝의라멘','서울 마포구 양화로7길 6-5','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('만두란','서울 마포구 동교로 81','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('커넥츠커피','서울 마포구 월드컵로11길 8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('함반','서울 마포구 월드컵로1길 54','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('포썸','서울 마포구 희우정로 77','아시아',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('태그어스','서울 마포구 월드컵로29길 25','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('버터크림팩토리','서울 마포구 망원로11길 41','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('장화신은고양이','서울 마포구 월드컵로19길 16','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('아마','서울 마포구 희우정로16길 46','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('604seoul','서울 마포구 동교로 49','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('바림케이크','서울 마포구 성미산로19길 21','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('알버트파크','서울 마포구 연남로3길 72','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('젤라떼리아 에따','서울 마포구 월드컵북로4길 44','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('파이인더샵','서울 마포구 성미산로27길 26','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('파롤앤랑그','서울 마포구 성미산로29길안길 8','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('란콰이진','서울 마포구 성미산로29안길 27-6','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('공간 비선형','서울 마포구 동교로 253','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('메종조','서울 서초구 반포대로7길 35','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오월의종','서울 용산구 이태원로49길 24','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('10월 19일','서울 서초구 반포대로3길 31','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('부엌쟁이','서울 동작구 동작대로23길 31','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('감나무집감자옹심이','강원 속초시 중앙시장로 110-8','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('오프더월','강원 강릉시 토성로 133','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카페밀','강원 강릉시 창해로 361-51','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('뉴문','부산 해운대구 양운로 56','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('빵다무르','부산 해운대구 해운대로781번길 16','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('빵빵빵','부산 해운대구 마린시티1로 91','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('수변최고돼지국밥','부산 수영구 광안해변로370번길 9-32','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('도어블','대전 중구 대흥로 117','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('바담칼국수','경기 시흥시 오이도로157번길 1','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('밀즈','대구 중구 봉산문화2길 42-15','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('슬로우터틀 동성로점','대구 중구 동성로2길 18-14','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('대봉정','대구 중구 명덕로 249','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('미남장어','대구 수성구 들안로 56','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('목련양과','대구 수성구 들안로8길 29','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('로칸다','대구 수성구 무학로27길 47','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('슬로우라이프','대구 수성구 동대구로77길 33-4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('잠석레스토랑','대구 달서구 월곡로53길 61','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('감포생아구','대구 수성구 상록로6','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('라이키마카롱','대구 동구 효신로5길 86','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('티제이버거','대구 수성구 화랑로2길 114','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('올리몰리','대구 동구 화랑로37길 12','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('레헴커피','대구 동구 동촌로58길 25','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('멜라이드','대구 수성구 동대구로42길 18','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('미즈컨테이너','경북 경산시 진량읍 대구대로 201','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('브라우니','경북 경산시 청운로 14-3','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('밀곳간','서울 성북구 성북로18길 19','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('아케미','서울 성북구 창경궁로 318','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('르셀','서울 성동구 상원10길 25','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('만동제과','서울 서대문구 연희로 32','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('우주옥','서울 마포구 동교로50길 11','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('씨스터브레드','서울 마포구 동교로52길 20-4','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('김보람초콜릿','서울 마포구 연희로 31','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('조비스그릴','서울 성북구 성북로 110','아시아',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('쥬똉뷔뜨','서울 송파구 백제고분로40길 16','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('우프','서울 송파구 백제고분로41길 25','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('노티드 청담','서울 강남구 도산대로53길 15','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('쎄쎄종','서울 강남구 언주로146길 39','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('천장지구','서울 강남구 언주로150길 51','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('라티지','서울 강남구 선릉로134길 5','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('라그랑자트','서울 강남구 도산대로62길 12','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('슬로우치즈','서울 강남구 삼성로145길 13','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('무니','서울 강남구 도산대로72길 16','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('에이뿔램','서울 강남구 도산대로102길 5','한식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('치즈룸','서울 강남구 논현로 854','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('작은뜰','서울 강남구 언주로133길 15','양식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('밀갸또','서울 서초구 서초대로58길 37','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('메리포핀스','대구 동구 국채보상로159길 12','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('우육면관','서울 종로구 청계천로 75-2','중식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('워터스트리트','서울 용산구 회나무로13가길 3-9 ','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('모리라멘&돈카츠','서울 관악구 남부순환로 2068','일식',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('더 셰프','서울 용산구 백범로77길 33','기타',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('카페이마','서울 종로구 세종대로 152','카페',null);
Insert into DINER (NAME,LOCATION,CATEGORY,FILE_ID) values ('앙시엔','서울 종로구 계동길 5','카페',null);


commit;

insert into board (title, content, writer, diner_seq, parent) values ('여기 맛있음', 'ㄱㄱ', 'sol@bhs.com', (select seq from diner where name='카레'), null);
insert into board (title, content, writer, diner_seq, parent) values ('', 'ㄹㅇ', 'sol@bhs.com', (select seq from diner where name='카레'), (select seq from board where title='여기 맛있음'));
commit;
